/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("com.google.dagger:dagger:2.16")
    annotationProcessor("com.google.dagger:dagger-compiler:2.16")
}

application {
    // Define the main class for the application.
    mainClass.set("example.App")
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}